#!/usr/bin/env bash

files_in_order="
src/lib.lua
src/att.lua

src/draw.lua
src/misc.lua
src/move_funcs.lua
src/tbox.lua
src/view.lua

src/acts.lua
src/parents.lua
src/demo.lua
"

./pico_minifier -d $files_in_order > _compiled_dev.lua
./pico_minifier $files_in_order > _compiled_prod.lua
