#!/usr/bin/perl -Iminifier_lib/
use strict;
use warnings;
use experimental 'smartmatch';
use Alanxoc3::Pico8FormatUtil;
use Getopt::Long qw(GetOptions);

my $dev_mode;
GetOptions('dev' => \$dev_mode) or die "Usage: $0 [--dev]\n";

# Constants specific to Zeldo.
my %constants;

# Colors
$constants{'FPS'} = '60';
$constants{'CART_NAME'} = '"guitar-mike"';
$constants{'FADE_TIME'} = '1';

# Go through the actual minifying.
my @lines = <>;
chomp(@lines);
@lines = remove_comments(@lines);
@lines = remove_texts(@lines);
@lines = tokenize_lines(\@lines, \%constants);
@lines = single_quotes_to_double(@lines);

if ($dev_mode) {
   @lines = remove_spaces(@lines);
} else {
   @lines = remove_spaces(@lines);
   my %vars = populate_vars(@lines);
   @lines = tokenize_lines(\@lines, \%vars);
}

# Uncomment for each thing to go on its own line.
# Note that this is slightly more compression space.
# $lines[0] =~ s/([^\"]) ([^\"])/$1\n$2/g;
@lines = pop_text_logics(@lines);

my $file = join($dev_mode ? "\n" : "\n", @lines);
$file = multiline_string_replace($file);
print $file;
